CREATE DATABASE jbook;
USE jbook;

DROP TABLE IF EXISTS `notebook_notes`;
CREATE TABLE `notebook_notes` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`notebook_id` INT NOT NULL DEFAULT '0' COMMENT '文集id',
	`note_id` INT NOT NULL DEFAULT '0' COMMENT '文章id',
	`created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY ( `id` ) USING BTREE 
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `notebooks`;
CREATE TABLE `notebooks` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`uid` INT UNSIGNED NOT NULL DEFAULT '0' COMMENT '关联用户id',
	`name` VARCHAR ( 64 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '文集名称',
	`created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY ( `id` ) USING BTREE 
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE `notes` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`uid` INT UNSIGNED NOT NULL DEFAULT '0' COMMENT '关联用户id',
	`title` VARCHAR ( 64 ) CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '文章名',
	`content_md` LONGTEXT CHARACTER 
	SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '文章内容',
	`state` TINYINT NOT NULL,
	`created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY ( `id` ) USING BTREE 
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;